name: Himelshop Client Website CI/CD [DEV]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --force
    - run: npm run build
#     - run: npm start & npx wait-on http://localhost:3000

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Re-install dependencies in server
      run: npm install --force
    - name: Start building
      run: npm run build
    - name: Restart PM2 application
      run: pm2 restart dev-client
#       run: pm2 serve build 3000 --spa --name "dev-client"
